version: '3'
services:
  php-cli:
    volumes:
      - './src:/app'
  nginx:
    ports:
      - "8080:80"
    environment:
      - TZ=${TZ}
    volumes:
      - './src/public:/app/public'
  php-fpm:
    volumes:
      - './src:/app'
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      - TZ=${TZ}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_db:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
  test-mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      - TZ=${TZ}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
volumes:
  mysql_db:
